name: Check for updates in template repository
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: "0 * * * *" # Once an hour at 00:00
jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install copier
        run: pip3 install copier

      - name: Check if update is available
        continue-on-error: false
        id: check
        run: |
          CHANGES=0
          if [ -f .cruft.json ]; then
            if ! cruft check; then
              CHANGES=1
            fi
          else
            echo "No .cruft.json file"
          fi

          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Run update if available
        id: update
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          copier update --skip-answered
          git restore --staged .
          if [ -z "$(git status --porcelain)" ]; then
            CHANGES=0
          else
            CHANGES=1
          fi
          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Create pull request
        if: steps.update.outputs.has_changes == '1'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .
          commit-message: "Merge updates from template repository"
          branch: copier/update
          delete-branch: true
          title: ğŸ‘¨â€ğŸ”§ Merge updates from template repository
          body: |
            This repository must be kept in sync with the template repository.

            This is an autogenerated PR. [Copier](https://copier.readthedocs.io/en/latest/) has detected updates in the template repository.
